<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260327093521 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, start__date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deadline TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, archived BOOLEAN NOT NULL, status_id INT DEFAULT NULL, tag_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE6BF700BD ON project (status_id)');
        $this->addSql('CREATE INDEX IDX_2FB3D0EEBAD26311 ON project (tag_id)');
        $this->addSql('CREATE TABLE project_users (project_id INT NOT NULL, users_id INT NOT NULL, PRIMARY KEY (project_id, users_id))');
        $this->addSql('CREATE INDEX IDX_7D6AC77166D1F9C ON project_users (project_id)');
        $this->addSql('CREATE INDEX IDX_7D6AC7767B3B43D ON project_users (users_id)');
        $this->addSql('CREATE TABLE status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tache (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, deadline TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id_project_id INT DEFAULT NULL, id_status_id INT DEFAULT NULL, id_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_93872075B3E79F4B ON tache (id_project_id)');
        $this->addSql('CREATE INDEX IDX_93872075EBC2BC9A ON tache (id_status_id)');
        $this->addSql('CREATE INDEX IDX_9387207579F37AE5 ON tache (id_user_id)');
        $this->addSql('CREATE TABLE tache_tag (tache_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (tache_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_378A7445D2235D39 ON tache_tag (tache_id)');
        $this->addSql('CREATE INDEX IDX_378A7445BAD26311 ON tache_tag (tag_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE time_table (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start__date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id_user_id INT DEFAULT NULL, id_tache_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B35B6E3A79F37AE5 ON time_table (id_user_id)');
        $this->addSql('CREATE INDEX IDX_B35B6E3A82F8B1AC ON time_table (id_tache_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first__name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, access_level VARCHAR(255) NOT NULL, contract_type VARCHAR(255) NOT NULL, enter_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE6BF700BD FOREIGN KEY (status_id) REFERENCES status (id)  ON DELETE SET NULL');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id)  ON DELETE SET NULL');
        $this->addSql('ALTER TABLE project_users ADD CONSTRAINT FK_7D6AC77166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_users ADD CONSTRAINT FK_7D6AC7767B3B43D FOREIGN KEY (users_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT FK_93872075B3E79F4B FOREIGN KEY (id_project_id) REFERENCES project (id)  ON DELETE SET NULL');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT FK_93872075EBC2BC9A FOREIGN KEY (id_status_id) REFERENCES status (id)  ON DELETE SET NULL');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT FK_9387207579F37AE5 FOREIGN KEY (id_user_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE tache_tag ADD CONSTRAINT FK_378A7445D2235D39 FOREIGN KEY (tache_id) REFERENCES tache (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tache_tag ADD CONSTRAINT FK_378A7445BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE time_table ADD CONSTRAINT FK_B35B6E3A79F37AE5 FOREIGN KEY (id_user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE time_table ADD CONSTRAINT FK_B35B6E3A82F8B1AC FOREIGN KEY (id_tache_id) REFERENCES tache (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EE6BF700BD');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EEBAD26311');
        $this->addSql('ALTER TABLE project_users DROP CONSTRAINT FK_7D6AC77166D1F9C');
        $this->addSql('ALTER TABLE project_users DROP CONSTRAINT FK_7D6AC7767B3B43D');
        $this->addSql('ALTER TABLE tache DROP CONSTRAINT FK_93872075B3E79F4B');
        $this->addSql('ALTER TABLE tache DROP CONSTRAINT FK_93872075EBC2BC9A');
        $this->addSql('ALTER TABLE tache DROP CONSTRAINT FK_9387207579F37AE5');
        $this->addSql('ALTER TABLE tache_tag DROP CONSTRAINT FK_378A7445D2235D39');
        $this->addSql('ALTER TABLE tache_tag DROP CONSTRAINT FK_378A7445BAD26311');
        $this->addSql('ALTER TABLE time_table DROP CONSTRAINT FK_B35B6E3A79F37AE5');
        $this->addSql('ALTER TABLE time_table DROP CONSTRAINT FK_B35B6E3A82F8B1AC');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE project_users');
        $this->addSql('DROP TABLE status');
        $this->addSql('DROP TABLE tache');
        $this->addSql('DROP TABLE tache_tag');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE time_table');
        $this->addSql('DROP TABLE users');
    }
}
